import { Router, Request, Response } from 'express';

export const materialsRoutes = Router();

export interface MaterialItem {
  id: string;
  category: string;
  name: string;
  spec: string;
  unit: string;
  basePriceLagos: number;
  priceFormatted: string;
  trend: 'UP' | 'DOWN' | 'STABLE';
  weeklyChange: string;
  description: string;
}

export const NIGERIA_BUILDING_MATERIALS: MaterialItem[] = [
  // CEMENT & BINDERS
  {
    id: 'mat-cem-01',
    category: 'Cement & Binders',
    name: 'Dangote 3X Portland Cement',
    spec: 'Grade 42.5N High-Strength Portland',
    unit: '50kg bag',
    basePriceLagos: 8600,
    priceFormatted: '₦8,400 - ₦8,800',
    trend: 'STABLE',
    weeklyChange: '-1.0%',
    description: 'General purpose structural concrete, foundation casting & block making.',
  },
  {
    id: 'mat-cem-02',
    category: 'Cement & Binders',
    name: 'BUA Extra Cement',
    spec: 'Grade 42.5N / Portland Composite',
    unit: '50kg bag',
    basePriceLagos: 8400,
    priceFormatted: '₦8,300 - ₦8,650',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'High workability cement for reinforced columns, beams & plastering.',
  },
  {
    id: 'mat-cem-03',
    category: 'Cement & Binders',
    name: 'Elephant / Lafarge Supaset',
    spec: 'Rapid Hardening Portland Cement',
    unit: '50kg bag',
    basePriceLagos: 8550,
    priceFormatted: '₦8,450 - ₦8,750',
    trend: 'STABLE',
    weeklyChange: '-0.5%',
    description: 'Early strength development ideal for precast blocks and suspended slabs.',
  },
  {
    id: 'mat-cem-04',
    category: 'Cement & Binders',
    name: 'POP Plaster of Paris Casting Powder',
    spec: 'Gypsum Calcined Finish Standard',
    unit: '40kg bag',
    basePriceLagos: 11000,
    priceFormatted: '₦10,500 - ₦12,000',
    trend: 'STABLE',
    weeklyChange: '+1.5%',
    description: 'False ceiling moulding, cornices, medallions & wall screeding.',
  },
  {
    id: 'mat-cem-05',
    category: 'Cement & Binders',
    name: 'White Cement (Birchwood / Superwhite)',
    spec: 'Decorative Silica Portland',
    unit: '40kg bag',
    basePriceLagos: 23500,
    priceFormatted: '₦22,000 - ₦25,000',
    trend: 'UP',
    weeklyChange: '+2.0%',
    description: 'Tile grouting, marble installations & architectural terrazzo works.',
  },

  // STEEL & REINFORCEMENT
  {
    id: 'mat-stl-01',
    category: 'Steel & Rebar',
    name: '10mm High-Yield TMT Rebar',
    spec: 'FE 500 High-Tensile Certified Steel',
    unit: 'Ton (~135 lengths)',
    basePriceLagos: 1160000,
    priceFormatted: '₦1,160,000',
    trend: 'UP',
    weeklyChange: '+2.5%',
    description: 'Slab reinforcement, stirrups, ring beams and lintels.',
  },
  {
    id: 'mat-stl-02',
    category: 'Steel & Rebar',
    name: '12mm High-Yield TMT Rebar',
    spec: 'FE 500 High-Tensile Certified Steel',
    unit: 'Ton (~94 lengths)',
    basePriceLagos: 1180000,
    priceFormatted: '₦1,180,000',
    trend: 'UP',
    weeklyChange: '+3.1%',
    description: 'Primary structural steel for floor slabs, columns, and foundations.',
  },
  {
    id: 'mat-stl-03',
    category: 'Steel & Rebar',
    name: '16mm High-Yield TMT Rebar',
    spec: 'FE 500 Structural Heavy-Duty Grade',
    unit: 'Ton (~53 lengths)',
    basePriceLagos: 1220000,
    priceFormatted: '₦1,220,000',
    trend: 'UP',
    weeklyChange: '+2.8%',
    description: 'Multi-storey building columns, heavy transfer beams, and retaining walls.',
  },
  {
    id: 'mat-stl-04',
    category: 'Steel & Rebar',
    name: '20mm High-Yield TMT Rebar',
    spec: 'FE 500 Structural Column Grade',
    unit: 'Ton (~34 lengths)',
    basePriceLagos: 1250000,
    priceFormatted: '₦1,250,000',
    trend: 'UP',
    weeklyChange: '+2.0%',
    description: 'Raft foundation basements, high-rise pillars & civil infrastructure.',
  },
  {
    id: 'mat-stl-05',
    category: 'Steel & Rebar',
    name: 'Binding Wire (Heavy Gauge)',
    spec: 'Annealed Flexible Tying Wire',
    unit: '25kg roll / bundle',
    basePriceLagos: 40000,
    priceFormatted: '₦38,000 - ₦42,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Tying and interlocking reinforcement steel bars before concrete pour.',
  },
  {
    id: 'mat-stl-06',
    category: 'Steel & Rebar',
    name: 'BRC Reinforcement Mesh Wire',
    spec: 'Ref 65 / Ref 142 Welded Mesh',
    unit: 'Roll (2.4m x 48m)',
    basePriceLagos: 75000,
    priceFormatted: '₦65,000 - ₦85,000',
    trend: 'STABLE',
    weeklyChange: '+0.5%',
    description: 'German floor oversite concrete, ground slabs, and driveway crack control.',
  },

  // AGGREGATES, SAND & BLOCKS
  {
    id: 'mat-agg-01',
    category: 'Blocks & Aggregates',
    name: '3/4 inch Clean Black Granite',
    spec: 'Foundation & Structural Slab Aggregate',
    unit: '30-ton tipper load',
    basePriceLagos: 285000,
    priceFormatted: '₦280,000 - ₦310,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Crushed quarry rock for heavy load-bearing structural concrete.',
  },
  {
    id: 'mat-agg-02',
    category: 'Blocks & Aggregates',
    name: '1/2 inch Clean Granite Aggregate',
    spec: 'Slab & Thin Section Concrete',
    unit: '30-ton tipper load',
    basePriceLagos: 295000,
    priceFormatted: '₦290,000 - ₦325,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Pre-stressed lintels, cantilever slabs & fine aggregate concrete.',
  },
  {
    id: 'mat-agg-03',
    category: 'Blocks & Aggregates',
    name: 'Clean Washed Sharp Sand',
    spec: 'River Dredged Silica Concrete Sand',
    unit: '20-ton tipper load',
    basePriceLagos: 145000,
    priceFormatted: '₦140,000 - ₦165,000',
    trend: 'STABLE',
    weeklyChange: '-1.5%',
    description: 'German floor casting, beam pouring, and heavy screed mix.',
  },
  {
    id: 'mat-agg-04',
    category: 'Blocks & Aggregates',
    name: 'Soft Plastering Sand',
    spec: 'Fine Smooth Silica Mortar Sand',
    unit: '20-ton tipper load',
    basePriceLagos: 130000,
    priceFormatted: '₦120,000 - ₦140,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Internal & external wall plastering and rendering.',
  },
  {
    id: 'mat-agg-05',
    category: 'Blocks & Aggregates',
    name: 'Hardcore Filling Stone',
    spec: 'Quarry Rubble / Boulders',
    unit: '30-ton tipper load',
    basePriceLagos: 225000,
    priceFormatted: '₦210,000 - ₦245,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Foundation base stabilization and swampy ground consolidation.',
  },
  {
    id: 'mat-agg-06',
    category: 'Blocks & Aggregates',
    name: '9-inch Solid Sandcrete Blocks',
    spec: 'Machine Vibrated 1:6 Mix Certified',
    unit: 'per piece delivered',
    basePriceLagos: 850,
    priceFormatted: '₦820 - ₦900',
    trend: 'DOWN',
    weeklyChange: '-2.0%',
    description: 'Foundation footing walls and load-bearing ground perimeter walls.',
  },
  {
    id: 'mat-agg-07',
    category: 'Blocks & Aggregates',
    name: '9-inch Hollow Sandcrete Blocks',
    spec: 'Machine Vibrated Standard',
    unit: 'per piece delivered',
    basePriceLagos: 760,
    priceFormatted: '₦720 - ₦800',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'External super-structure perimeter walls.',
  },
  {
    id: 'mat-agg-08',
    category: 'Blocks & Aggregates',
    name: '6-inch Solid Sandcrete Blocks',
    spec: 'Machine Vibrated Internal Partition',
    unit: 'per piece delivered',
    basePriceLagos: 700,
    priceFormatted: '₦680 - ₦750',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Internal non-loadbearing dividing walls and room partitions.',
  },
  {
    id: 'mat-agg-09',
    category: 'Blocks & Aggregates',
    name: 'Heavy-Duty Interlocking Paving Stones',
    spec: '60mm / 80mm Hydraulic Pressed',
    unit: 'sq. meter (~40-50 units)',
    basePriceLagos: 5800,
    priceFormatted: '₦5,200 - ₦6,800',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Driveways, walkways, compound landscaping & heavy vehicular parking.',
  },

  // ROOFING & TIMBER
  {
    id: 'mat-rf-01',
    category: 'Roofing & Wood',
    name: '0.55mm Aluminium Longspan Roofing Sheet',
    spec: 'Oven-Baked Anti-Corrosion Coil',
    unit: 'per sq. meter',
    basePriceLagos: 8100,
    priceFormatted: '₦7,800 - ₦8,500',
    trend: 'STABLE',
    weeklyChange: '+0.5%',
    description: 'Long-life residential and commercial weather-resistant roofing.',
  },
  {
    id: 'mat-rf-02',
    category: 'Roofing & Wood',
    name: 'Stone-Coated Metal Roofing Tiles',
    spec: '0.45mm Bond / Shingle / Roman Design',
    unit: 'per panel',
    basePriceLagos: 5100,
    priceFormatted: '₦4,600 - ₦5,800',
    trend: 'UP',
    weeklyChange: '+1.5%',
    description: 'Sound-proof, fire-resistant luxury aesthetic stone chip tiles.',
  },
  {
    id: 'mat-rf-03',
    category: 'Roofing & Wood',
    name: 'Hardwood Timber 2x4 (12 feet)',
    spec: 'Obeche / Mahogany Seasoned Timber',
    unit: 'per length',
    basePriceLagos: 2400,
    priceFormatted: '₦2,200 - ₦2,600',
    trend: 'UP',
    weeklyChange: '+2.0%',
    description: 'Roof trusses, kingposts, rafters and column formwork bracing.',
  },
  {
    id: 'mat-rf-04',
    category: 'Roofing & Wood',
    name: 'Hardwood Timber 2x3 (12 feet)',
    spec: 'Seasoned Structural Timber',
    unit: 'per length',
    basePriceLagos: 1750,
    priceFormatted: '₦1,600 - ₦1,900',
    trend: 'UP',
    weeklyChange: '+1.0%',
    description: 'Roof purlins and ceiling nogging frameworks.',
  },
  {
    id: 'mat-rf-05',
    category: 'Roofing & Wood',
    name: '18mm Marine Waterproof Plywood',
    spec: 'Phenolic Film-Faced Shuttering Board',
    unit: 'Sheet (4ft x 8ft)',
    basePriceLagos: 26000,
    priceFormatted: '₦24,000 - ₦28,000',
    trend: 'UP',
    weeklyChange: '+3.0%',
    description: 'Fair-face concrete formwork, decking slabs & cantilever beams.',
  },

  // PLUMBING & WATER SUPPLY
  {
    id: 'mat-plm-01',
    category: 'Plumbing & Pipes',
    name: '4-inch PVC Soil & Waste Pipe',
    spec: 'Class B / Class C Heavy-Gauge 5.8m',
    unit: 'per 5.8m length',
    basePriceLagos: 9500,
    priceFormatted: '₦8,500 - ₦12,500',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Water closet drainage stack, inspection chambers & manhole drops.',
  },
  {
    id: 'mat-plm-02',
    category: 'Plumbing & Pipes',
    name: '3/4 inch PPR Hot & Cold Water Pipe',
    spec: 'PN 20 High-Pressure Polypropylene 4m',
    unit: 'per 4m length',
    basePriceLagos: 4200,
    priceFormatted: '₦3,800 - ₦4,600',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Concealed internal hot/cold water distribution with zero corrosion.',
  },
  {
    id: 'mat-plm-03',
    category: 'Plumbing & Pipes',
    name: '1000 Litres Overhead Water Tank',
    spec: 'Cylindrical Heavy-Duty Polyethylene',
    unit: 'per unit',
    basePriceLagos: 82000,
    priceFormatted: '₦75,000 - ₦90,000',
    trend: 'STABLE',
    weeklyChange: '+1.0%',
    description: 'Clean domestic gravity-fed potable water storage.',
  },
  {
    id: 'mat-plm-04',
    category: 'Plumbing & Pipes',
    name: '2000 Litres Overhead Water Tank',
    spec: 'GeePee / Topcon UV-Stabilized',
    unit: 'per unit',
    basePriceLagos: 145000,
    priceFormatted: '₦135,000 - ₦160,000',
    trend: 'STABLE',
    weeklyChange: '+1.0%',
    description: 'High-capacity residential and commercial overhead water storage.',
  },
  {
    id: 'mat-plm-05',
    category: 'Plumbing & Pipes',
    name: '1.5HP Submersible Borehole Pump',
    spec: 'Deep Well Single-Phase with Control Box',
    unit: 'per unit',
    basePriceLagos: 165000,
    priceFormatted: '₦145,000 - ₦195,000',
    trend: 'UP',
    weeklyChange: '+2.5%',
    description: 'Underground deep borehole groundwater extraction.',
  },

  // ELECTRICAL & WIRING
  {
    id: 'mat-elec-01',
    category: 'Electrical',
    name: '2.5mm Single-Core Copper Cable',
    spec: '100% Pure Copper 100m (Coleman/Nigerchin)',
    unit: '100m roll',
    basePriceLagos: 41000,
    priceFormatted: '₦38,000 - ₦44,000',
    trend: 'UP',
    weeklyChange: '+3.0%',
    description: 'Standard 13A ring main power sockets and domestic appliances.',
  },
  {
    id: 'mat-elec-02',
    category: 'Electrical',
    name: '1.5mm Single-Core Copper Cable',
    spec: '100% Pure Copper 100m (Certified)',
    unit: '100m roll',
    basePriceLagos: 26000,
    priceFormatted: '₦24,000 - ₦28,000',
    trend: 'UP',
    weeklyChange: '+2.0%',
    description: 'Internal lighting points, ceiling fans & inverter circuits.',
  },
  {
    id: 'mat-elec-03',
    category: 'Electrical',
    name: '4.0mm Single-Core Copper Cable',
    spec: 'Heavy Load 100m (Certified)',
    unit: '100m roll',
    basePriceLagos: 62000,
    priceFormatted: '₦58,000 - ₦68,000',
    trend: 'UP',
    weeklyChange: '+3.5%',
    description: 'Air conditioning, water heaters, electric cookers & pumping machines.',
  },
  {
    id: 'mat-elec-04',
    category: 'Electrical',
    name: '16mm 4-Core Armoured Cable',
    spec: 'Steel Wire Armoured (SWA) Underground',
    unit: 'per meter',
    basePriceLagos: 21000,
    priceFormatted: '₦18,500 - ₦24,000',
    trend: 'UP',
    weeklyChange: '+4.0%',
    description: 'Main incoming electricity supply feeder from transformer / generator.',
  },

  // TILES, FINISHING & PAINTS
  {
    id: 'mat-fin-01',
    category: 'Tiles & Paints',
    name: '60x60cm Vitrified Floor Tiles',
    spec: 'High-Gloss Stain-Resistant Glazed',
    unit: 'sq. meter (~4 tiles/box)',
    basePriceLagos: 11000,
    priceFormatted: '₦9,500 - ₦14,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Living room, hallway, and master bedroom luxury floor tiling.',
  },
  {
    id: 'mat-fin-02',
    category: 'Tiles & Paints',
    name: '30x60cm Ceramic Wall Tiles',
    spec: 'Glazed Water-Resistant Tile',
    unit: 'sq. meter (~8 tiles/box)',
    basePriceLagos: 5500,
    priceFormatted: '₦4,800 - ₦6,500',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Kitchen backsplashes, shower enclosures & bathroom walls.',
  },
  {
    id: 'mat-fin-03',
    category: 'Tiles & Paints',
    name: 'Dulux / Meyer Emulsion Paint',
    spec: 'Premium Matt Finish 20L Bucket',
    unit: '20L bucket',
    basePriceLagos: 38000,
    priceFormatted: '₦32,000 - ₦48,000',
    trend: 'STABLE',
    weeklyChange: '+1.0%',
    description: 'Smooth washable interior/exterior architectural wall coating.',
  },
  {
    id: 'mat-fin-04',
    category: 'Tiles & Paints',
    name: 'Security Steel Entrance Door (3ft x 7ft)',
    spec: 'Multi-Lock Heavy-Duty Turkish Grade',
    unit: 'per complete unit with frame',
    basePriceLagos: 245000,
    priceFormatted: '₦185,000 - ₦350,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Bullet-resistant security front entrance door.',
  },
  {
    id: 'mat-fin-05',
    category: 'Tiles & Paints',
    name: 'Internal Flush Wooden Door with Casing',
    spec: 'HDF Moulded Panel with Lockset',
    unit: 'per unit',
    basePriceLagos: 58000,
    priceFormatted: '₦45,000 - ₦75,000',
    trend: 'STABLE',
    weeklyChange: '0.0%',
    description: 'Bedrooms, study rooms & internal hallway door installations.',
  },
];

materialsRoutes.get('/', (req: Request, res: Response) => {
  const { category, state } = req.query;

  let list = NIGERIA_BUILDING_MATERIALS;

  if (category && typeof category === 'string' && category !== 'All') {
    list = list.filter((m) => m.category.toLowerCase() === category.toLowerCase());
  }

  // Adjust prices slightly for non-Lagos states based on regional haulage logistics
  if (state && typeof state === 'string') {
    const isNorth = state.includes('Kano') || state.includes('Kaduna') || state.includes('Abuja') || state.includes('Jos') || state.includes('Borno');
    const isEast = state.includes('Rivers') || state.includes('Enugu') || state.includes('Anambra') || state.includes('Delta');

    const factor = isNorth ? 1.05 : (isEast ? 1.03 : 1.0);

    const adjusted = list.map((item) => {
      if (factor === 1.0) return item;
      const newBase = Math.round((item.basePriceLagos * factor) / 100) * 100;
      return {
        ...item,
        basePriceLagos: newBase,
      };
    });

    return res.json({
      success: true,
      totalCount: adjusted.length,
      data: adjusted,
    });
  }

  return res.json({
    success: true,
    totalCount: list.length,
    data: list,
  });
});
